# Generated by Django 5.2.1 on 2025-05-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='d_img',
            field=models.FileField(upload_to='destination'),
        ),
    ]
