# Generated by Django 5.2.1 on 2025-05-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0002_alter_destinations_d_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_colour', models.CharField(max_length=50)),
                ('car_img', models.FileField(upload_to='cars')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='discription',
            field=models.TextField(),
        ),
    ]
