# Generated by Django 5.2.1 on 2025-05-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0003_cars_booking_contact_alter_booking_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
