# Generated by Django 5.2.1 on 2025-05-27 19:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0005_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='d_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
